from django.urls import path,include
from . import views
urlpatterns=[
    path('',views.projecthomepage,name='projecthomepage'),
    #path('projectstudentpage/',views.projectstudentpage,name='studentpage'),
    path('printpagecall/',views.printpagecall,name='printpagecall'),
    path('prin ptpagelogic/',views.printpagelogic,name='printpagelogic'),
    path('exceptionpagecall',views.exceptionpagecall,name='exceptionpagecall'),
    path('exceptionpagelogic',views.exceptionpagelogic,name='exceptionpagelogic'),
    path('randompagelogic/',views.randompagelogic,name='randompagelogic'),
    path('randomcall/',views.randomcall,name='randomcall'),
    path('calculatorcall/',views.calculatorcall,name='calculatorcall'),
    path('calculatorlogic',views.calculatorlogic,name='calculatorlogic'),
    path('datetimepagecall/', views.datetimepagecall,name='datetimepagecall'),
    path('datetimepagelogic', views.datetimepagelogic,name='datetimepagelogic'),
    path('add_task/',views.add_task,name='add_task'),
    path('<int:pk>/delete/',views.delete_task,name='delete_task'),
    path('UserRegisterPageCall',views.UserRegisterPageCall,name='UserRegisterPageCall'),
    path('UserRegisterLogic',views.UserRegisterLogic,name='UserRegisterLogic'),
    path('UserLoginPageCall/', views.UserLoginPageCall, name='UserLoginPageCall'),
    path('UserLoginLogic/', views.UserLoginLogic, name='UserLoginLogic'),
    path('logout/', views.logout, name='logout'),
    path('add_student/',views.add_student,name='add_student'),
    path('student_list/',views.student_list,name='student_list'),
    path('StudentListCall/',views.StudentListCall,name='StudentListCall'),
    path('AddStudentCall/',views.AddStudentCall,name='AddStudentCall'),
    path('upload_file/',views.upload_file,name='upload_file'),
    path('user_feedback/',views.user_feedback,name='user_feedback'),
    path('contact_manager/', views.contact_manager, name='contact_manager'),
]